function createfigure(Y1, Y2)
%CREATEFIGURE(Y1, Y2)
%  Y1:  vector of y data
%  Y2:  vector of y data

%  Auto-generated by MATLAB on 24-Nov-2020 08:28:05

% Create figure
figure1 = figure;

% Create axes
axes1 = axes('Parent',figure1);
hold(axes1,'on');

% Activate the left side of the axes
yyaxis(axes1,'left');
% Create plot
plot(Y1,'Marker','.','LineStyle','none','Color',[0 0 1]);

% Create ylabel
ylabel('I(t) [\muU/ml]');

% Set the remaining axes properties
set(axes1,'YColor',[0 0.447 0.741]);
% Activate the right side of the axes
yyaxis(axes1,'right');
% Create plot
plot(Y2,'LineWidth',2,'Color',[1 0 0]);

% Create ylabel
ylabel('v(t) [\muU/kg/min]');

% Set the remaining axes properties
set(axes1,'YColor',[0.85 0.325 0.098]);
% Create xlabel
xlabel('čas [min]');

% Uncomment the following line to preserve the X-limits of the axes
% xlim(axes1,[0 1040]);
% Set the remaining axes properties
set(axes1,'XTickLabel',...
    ['400 ';'500 ';'600 ';'700 ';'800 ';'900 ';'1000';'1100';'1200';'1300';'1400';'1500';'1600']);
